### ISSUE TITLE
Skylight

### ISSUE THREAD

**Issue by godisgood4** [Jeija/minetest-mod-weather#4]
When in a house with a skylight made of "default:glass," the rain pours even though it should not be able to pass through a glass surface. This is because the natural light passing through the glass causes the light level to equal 15.

![bug](https://cloud.githubusercontent.com/assets/18508540/15970739/1fd250de-2f04-11e6-9284-472336e0211b.png)

**Comment by HybridDog** [comment]
godisgood4, this mod is almost three years old, let me suggest you following: on github always look if there are newer forks, if it's the case, do not star the repository because starred one are shown first when using the github search field.
https://github.com/Jeija/minetest-mod-weather/network
Obviously xeranas has the newest version:
https://github.com/xeranas/weather_pack

**Comment by Jeija** [comment]
@HybridDog This is correct, I haven't been working on this mod for ages and even back then this mod was mostly just a proof-of-concept after I wrote the particle system. So, @godisgood4 , please check some more recent weather mods out there, and if your bug still occurs, report your bug there.
